services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
    container_name: frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - server
