services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
  server:
    build: ./server
    ports:
      - "8000:8000"
  nginx:
    build: ./.nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - server
